### ISSUE TITLE
Fails on ubuntu 21.10 with cypress 9.2.0

### ISSUE THREAD

**Issue by Hideman85** [bahmutov/demo-docker-cypress-included#12]
I tried the following docker-compose:
```yml
version: '3.7'
services:
  cypress:
    build:
      context: .
      dockerfile: ./Dockerfile.cypress
      network: host
    environment:
      - DISPLAY
    working_dir: /cypress
    entrypoint: ''
    command: bash -c 'cypress open --config baseUrl=http://localhost:3000'
    volumes:
      - ./cypress:/cypress/cypress
      - /tmp/.X11-unix:/tmp/.X11-unix
```

And I'm getting
```
cypress_1  | Gtk-Message: 13:21:05.791: Failed to load module "canberra-gtk-module"
cypress_1  | Gtk-Message: 13:21:05.792: Failed to load module "canberra-gtk-module"
cypress_1  | [17:0302/132105.799990:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
cypress_1  | [17:0302/132105.801664:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
cypress_1  | [17:0302/132105.801699:ERROR:bus.cc(392)] Failed to connect to the bus: Address does not contain a colon
cypress_1  | [17:0302/132105.849082:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [17:0302/132105.849101:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 1 time(s)
cypress_1  | [17:0302/132105.858609:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [17:0302/132105.858630:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 2 time(s)
cypress_1  | [17:0302/132105.867367:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [17:0302/132105.867386:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 3 time(s)
cypress_1  | [17:0302/132105.875058:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [17:0302/132105.875074:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 4 time(s)
cypress_1  | [17:0302/132105.961576:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [17:0302/132105.961592:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 5 time(s)
cypress_1  | [17:0302/132105.968154:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=1024
cypress_1  | [17:0302/132105.968172:WARNING:gpu_process_host.cc(1270)] The GPU process has crashed 6 time(s)
cypress_1  | [17:0302/132105.968182:FATAL:gpu_data_manager_impl_private.cc(417)] GPU process isn't usable. Goodbye.
cypress_1  | The Test Runner unexpectedly exited via a exit event with signal SIGILL
```
